dataSourceProperties {
    dataSource {
        url="jdbc:h2:file:./persistence/persistence;DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0;LOCK_TIMEOUT=10000"
    }
}
devMode=true
myLegalName="O=Mridul,L=Bengaluru,C=IN"
p2pAddress="mridul:10011"
rpcSettings {
    address="0.0.0.0:10012"
    adminAddress="0.0.0.0:10032"
}
security {
    authService {
        dataSource {
            type=INMEMORY
            users=[
                {
                    password=test
                    password=${?CORDA_RPC_PASSWORD}
                    permissions=[
                        ALL
                    ]
                    user=user1
                    user=${?CORDA_RPC_USERNAME}
                }
            ]
        }
    }
}

