server.port=8080
spring.application.name=expense-chain-backend
spring.web.resources.static-locations=classpath:/static/
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Corda Nodes RPC Addresses
corda.nodes.Garvit.host=localhost
corda.nodes.Garvit.rpcPort=10006
corda.nodes.Garvit.username=user1
corda.nodes.Garvit.password=test
corda.nodes.Garvit.x500Name=O=Garvit,L=New Delhi,C=IN

corda.nodes.Arnav.host=localhost
corda.nodes.Arnav.rpcPort=10009
corda.nodes.Arnav.username=user1
corda.nodes.Arnav.password=test
corda.nodes.Arnav.x500Name=O=Arnav,L=Mumbai,C=IN

corda.nodes.Mridul.host=localhost
corda.nodes.Mridul.rpcPort=10012
corda.nodes.Mridul.username=user1
corda.nodes.Mridul.password=test
corda.nodes.Mridul.x500Name=O=Mridul,L=Bengaluru,C=IN

corda.notary.x500Name=O=Notary,L=London,C=GB
